steps:
  # 1. Run automated tests
  - name: 'python:3.12-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --no-cache-dir -r requirements.txt
        pytest

  # 2. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloudcart-repo/cloudcart:$BUILD_ID'
      - '.'

  # 3. Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloudcart-repo/cloudcart:$BUILD_ID'

  # 4. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cloudcart'
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/cloudcart-repo/cloudcart:$BUILD_ID'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=cloudcart-run-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars=USE_FIRESTORE=true,GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--min=0'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloudcart-repo/cloudcart:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY